### ISSUE TITLE
Favicon into team logo

### ISSUE THREAD

**Issue by Kapi2910** [Technocrats-nitw/TechnoWebLatest#1]
![Change This](https://user-images.githubusercontent.com/63846417/150912863-25ace4f3-51e9-4fa8-b5d6-d0f6610a2cce.png)

**Comment by Kapi2910** [comment]
@suffisme @anshuisme @chaitanyahardikar @ashiqa @Shaik2003

**Comment by Kapi2910** [comment]
@Kapi2910

**Comment by chaitanyahardikar** [comment]
We will work on it soon
